config/routes.rb
LinuxEndpoint::Application.routes.draw do #  get "resumes/index"

 # get "resumes/new"

 #get "resumes/create"

#  get "resumes/destroy"
  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :builds


  resources :projects


  resources :vmrequests


  get "home/index"
get "/search_list" => "home#search_list", :as => :search_list
get "/reports" => "vmrequests#reports", :as => :reports
get "/reports_search" => "vmrequests#reports_search", :as => :reports_search
get "export", to: "vmrequests#export", :as => :export
get "status_export", to: "projects#status_export", :as => :status_export

  get "sessions/new"

  resources :sessions

  match 'logout', to: 'sessions#destroy', as: 'logout'

  match 'login', to: 'sessions#new', as: 'login'

  match 'signup', to: 'users#new', as: 'signup'
   root :to => 'home#index'
end

app/models/vmrequest.rb
class Vmrequest < ActiveRecord::Base
  attr_accessible  :owner, :comments, :name, :requested_date, :references, :prob_desc, :solution, :proposal, :approval, :attachment, :adv 
  # attr_accessible :complete_date, :owner, :os_version, :other, :ticket_no, :project,, :comments, :cpus, :environment, :name, :os_type, :ram, :requested_date, :requester, :space, :status
 acts_as_xlsx
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true, uniqueness: {message: "Title already existing" }

# validates :name, uniqueness: {message: "VM already existing" }
# validates :requester, :format => {:with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i,
#     :message => 'format is Invalid' }

#SEARCHABLES
# searchable do 
#   text :name
#   text :owner
# end

end

app/controllers/vmrequests_controller.rb
class VmrequestsController < ApplicationController
  # GET /vmrequests
  # GET /vmrequests.json

  def reports
  end 
  def index
    #  @search = Vmrequest.search do
    #   fulltext params[:search]
    #   paginate  :page => params[:page], :per_page=>5
    # end
    # @vmrequests = @search.results
## @vmrequests = Vmrequest.page(params[:page]).per(7)   
@vmrequests = Vmrequest.all
# Kaminari.paginate_array(@vmrequests).page(params[:page]).per(3)
  end
  def reports_search
    from_date = params[:date][:day]+"-"+params[:date][:month]+"-"+params[:date][:year]
    tos_date = params[:to_date][:day]+"-"+params[:to_date][:month]+"-"+params[:to_date][:year]
    from_search = from_date.to_date
    tos_search = tos_date.to_date
    @vmrequests= Vmrequest.find(:all, :conditions=>["requested_date BETWEEN ? AND ? ", from_search, tos_search ])
  end 
   

  # GET /vmrequests/1
  # GET /vmrequests/1.json
  def show
    @vmrequest = Vmrequest.find(params[:id])

    
  end

  # GET /vmrequests/new
  # GET /vmrequests/new.json
  def new
    @vmrequest = Vmrequest.new
  end

  def export
    # @builds = Vmrequest.all
    @projects = Project.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end  

  # GET /vmrequests/1/edit
  def edit
    @vmrequest = Vmrequest.find(params[:id])
  end

  # POST /vmrequests
  # POST /vmrequests.json
   def create
    @vmrequest = Vmrequest.new(params[:vmrequest])
    respond_to do |format|
      if @vmrequest.save
        format.js
        @vmrequests = Vmrequest.all 

      end
    end
   end


  #  def create
  #   @vmrequest = Vmrequest.new(params[:vmrequest])
  #   respond_to do |format|
  #     if @vmrequest.save
  #       # MbsMailer.confirmation_mail(@vmrequest).deliver
  #       format.html { redirect_to @vmrequest, notice: 'Idea was successfully created.' }
  #       format.json { render json: @vmrequest, status: :created, location: @vmrequest }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @vmrequest.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /vmrequests/1
  # PUT /vmrequests/1.json
  def update
    @vmrequest = Vmrequest.find(params[:id])

    respond_to do |format|
      if @vmrequest.update_attributes(params[:vmrequest])
       format.js
       @vmrequests = Vmrequest.all
      else
        format.html { render action: "edit" }
        format.json { render json: @vmrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vmrequests/1
  # DELETE /vmrequests/1.json
  def destroy
    @vmrequest = Vmrequest.find(params[:id])
    @vmrequest.destroy
      redirect_to :action => :index, status:303
  end
end

app/helpers/vmrequests_helper.rb
module VmrequestsHelper

end

app/views/vmrequests/_form.html.erb
<div class ="container" style="width:85%;">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h3>New Idea </h3></div>
     
    </div>
  <%= form_for @vmrequest, html: { multipart: true }, remote: true do |f| %>

<%#= form_for(@vmrequest, remote: true) do |f| %>
  
<fieldset class="formfield">
<%= link_to 'Back', vmrequests_path, :remote=>true %>
 <p style="width:95%;">
    <label>Title*</label>
    <%= f.text_field :name %>
  </p>

  <p  style="width:50%;">
    <label> Owner*</label>
    <%= f.text_field :owner %>
  </p>

  <p>
    <label> Attachment</label>
    <%= f.file_field :attachment %>

  </p>

  <p style="width:95%;">
  <label>Abstract</label>
    <%= f.text_area:comments, :rows=>6,:columns=>5 %>
  </p>
   
  <p style="width:95%;">
  <label>Problem Description</label>
    <%= f.text_area:prob_desc, :rows=>4,:columns=>5 %>
  </p>
   <p style="width:95%;">
  <label>Solution</label>
    <%= f.text_area:solution, :rows=>5,:columns=>5 %>
  </p> 
   <p style="width:95%;">
  <label>Advantages</label>
    <%= f.text_area:adv, :rows=>5,:columns=>5 %>
  </p>
   <p style="width:95%;">
  <label>Proposal</label>
    <%= f.text_area:proposal, :rows=>6,:columns=>5 %>
  </p>
   <p>
  <label>References</label>
    <%= f.text_area:references, :rows=>4,:columns=>5 %>
  </p>
   <p>
  <label>Approved</label>
    <%= f.check_box:approval, :checked_value=> "1", :unchecked_value =>"0", :style=>"margin-top:10px;" %>
  </p>
   <p>
    <label>Date</label>
    <%= f.date_select :requested_date, :style=>"width:100px;", :value =>Date.today %>
  </p>

   <p>  <%= f.submit :class=>"btn btn-primary", :value=>"Create Idea", :remote=>true, :style=>"float:right;"%></p>
<% end %>
</fieldset>

<p>

<script>
$('document').ready(function(){
 $("form").submit(function(){
    $('input[type=submit]').attr('disabled', 'disabled');
  });

});
</script>

app/views/vmrequests/_index.html.erb
<!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h3>Ideas</h3></div>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">
<% comment do %>
          <%= form_tag vmrequests_path, :method => :get, :remote=> true do %>
          <%= text_field_tag :search, params[:search],:class=>"span2 search-query"  ,:style=>"height:32px;border:3px solid rgb(221,219,231);border-radius:14px 0 0 14px; margin-right:-10px;", :placeholder =>"Search By VM Name"%>
          <%= submit_tag "Search", :name => nil, :class=>"btn", :style=>"height:32px; border-radius:0 14px 14px 0;" %>
          <% end %>
  <% end %>
        </div>
      </div>
       <div style="float:right;"><%= link_to 'Create Idea', new_vmrequest_path, :remote=>true, :class=>"btn btn-warning"  %></div>
    </div>

  <table class="table table-hover tablesorter">

  <tr>
    <th>Sl.No</th>
    <th>Title</th>
    <th>Date</th>
    <th>Creator</th>
    <th>Download Link</th>
    <!-- <th style="text-align:center;font-size:19px;">Completion Date</th> -->
    <!-- <th style="text-align:center;font-size:19px;">Approval</th> -->
    <!-- <th style="text-align:center;font-size:19px;">Status</th> -->
    <!-- <th style="text-align:center;font-size:19px;">OS Type</th> -->
    <th colspan=3 style="text-align:center;"> Actions </th>
  </tr>
<% i =0 %>
<% @vmrequests.each do |vmrequest| %>
<% i= i+1%>
  <tr>
    <td><%= i %></td>
    <td ><%= vmrequest.name %></td>
    <td><%= vmrequest.requested_date %></td>
    <td><%= vmrequest.owner %></td>
    <!-- <td style="text-align:center;"><%= vmrequest.complete_date %></td> -->
    <!-- <td style="text-align:center;"><%= vmrequest.approval %></td> -->
    <!-- <td style="text-align:center;"><%= vmrequest.status %></td> -->
    <!-- <td style="text-align:center;"><%= vmrequest.os_type %></td> -->
    <% if vmrequest.attachment_url.present? %> 
    <td><%= link_to "Download Attachment", vmrequest.attachment_url %></td>
<% else %>
<td> No document attached </td>
    <% end %>
    <td style="text-align:center;"><%= link_to 'Show', vmrequest, :remote=>true, :class=>"btn btn-primary" %></td>
    <td style="text-align:center;"><%= link_to 'Edit', edit_vmrequest_path(vmrequest), :remote=>true, :class=>"btn btn-info"  %></td>
    <% if @current_user == "Vijaya Jyothi Kalangi (c)"|| "Ravi Kottapalli" || "Srinivas Hemige" %>
    <td style="text-align:center;"><%= link_to 'Remove', vmrequest, method: :delete, :remote=>true,data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger"  %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

</div>

app/views/vmrequests/_reports.html.erb
<div class ="container">
  <!-- Index form Started -->
   <div style="float:right;"><h4><%= link_to "Download Builds as Excel", export_path(format: "xlsx") %></h4></div>
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h3>Search Build Requests</h3></div>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">

<%= form_tag reports_search_path, :method => :get, :remote=> true do %>
<p> <label>From Date</label>
  <%= select_date()%></p>
  <p> <label>To Date</label>
  <%= select_date(Date.today, :prefix=>"to_date")%></p>
    <%#= date_select("to_date", "to_date", order:[:day, :month, :year]) %></p>
    <%#= date_field_tag :date2, params[:search2] %>
    <%= submit_tag "Search", :name => nil, :class=>"btn btn-primary" %>
    <% end %>


</div>
</div>

<div class="search-container">
</div>

app/views/vmrequests/_reports_search.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2>Builds</h2></div>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">

          
        </div>
      </div>
    </div>

  <table class="table table-striped tablesorter">

  <tr>
    <th>VM Name</th>
    <th>Requested date</th>
    <th>Approval</th>
    <th>Status</th>
    <th>Assignee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vmrequests.each do |vmrequest| %>
  <tr>
    <td><%= vmrequest.name %></td>
    <td><%= vmrequest.requested_date %></td>
    <td><%= vmrequest.approval %></td>
    <td><%= vmrequest.status %></td>
    <td><%= vmrequest.other %></td>
    <td><%= link_to 'Show', vmrequest, :remote=>true %></td>
    <td><%= link_to 'Edit', edit_vmrequest_path(vmrequest), :remote=>true %></td>
  </tr>
<% end %>
</table>

<br />



</div>

app/views/vmrequests/_show.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-12">
      <h2><%= @vmrequest.name.capitalize%> Details</h2></div>
     
    </div>
<p id="notice"><%= notice %></p>
<fieldset class="formfield">
<span style="float:right;"><%= link_to 'Back', vmrequests_path, :remote=>true %></span>

 <p style="font-size:14px;">
    <label> Title</label>
  <%= @vmrequest.name %>
</p>
<p style="font-size:14px;">
    <label> Owner</label>
  <%= @vmrequest.owner %>
</p>

<p style="font-size:14px;">
    <label> Abstract</label>
  <%= @vmrequest.comments %>
</p>


<p style="font-size:14px;">
    <label> Problem Description</label>
  <%= @vmrequest.prob_desc %>
</p>


<p style="font-size:14px;">
    <label> Solution</label>
  <%= @vmrequest.solution %>
</p>

<p style="font-size:14px;">
    <label> Advantages</label>
  <%= @vmrequest.adv %>
</p>


<p style="font-size:14px;">
    <label> Proposal</label>
  <%= @vmrequest.proposal %>
</p>



<p style="font-size:14px;">
  <label>References:</label>
  <%= @vmrequest.references %>
</p>


<p style="font-size:14px;">
  <label>Approval:</label>
  <%= @vmrequest.approval %>
</p>


</fieldset>
</div>

<%= link_to 'Edit', edit_vmrequest_path(@vmrequest), :remote=>true %> |


<style>
.formfield label { padding:4px;margin-top:0px !important; float: left; clear: left; display: block; width: 140px; padding-right: 20px; text-align: left; line-height: 15px; font-size:14px;}
.formfield p{
  width:100% !important;

}
<style>

app/views/vmrequests/create.js.erb
<%# if remotipart_submitted? %>
$(".landing-container").html("<%= escape_javascript(render(:partial => "index"))%>");

<%# else %>
  // alert('submitted via native jquery-ujs')
<%# end %>

app/views/vmrequests/destroy.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "index"))%>");

app/views/vmrequests/edit.html.erb
<h1>Editing vmrequest</h1>

<%= render 'form' %>

<%= link_to 'Show', @vmrequest, :remote=>true %> |
<%= link_to 'Back', vmrequests_path, :remote =>true %>

app/views/vmrequests/index.html.erb
<div class ="container">

<h1>Listing vmrequests</h1>

  <table class="table table-striped tablesorter">

  <tr>
    <th>VM Name</th>
    <th>Requested date</th>
    <th>Approval</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vmrequests.each do |vmrequest| %>
  <tr>
    <td><%= vmrequest.name %></td>
    <td><%= vmrequest.requested_date %></td>
    <td><%= vmrequest.approval %></td>
    <td><%= vmrequest.status %></td>
    <td><%= link_to 'Show', vmrequest %></td>
    <td><%= link_to 'Edit', edit_vmrequest_path(vmrequest) %></td>
    <td><%= link_to 'Destroy', vmrequest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vmrequest', new_vmrequest_path %>


</div>

app/views/vmrequests/reports.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "reports"))%>");

app/views/vmrequests/reports_search.js.erb
$(".search-container").html("<%= escape_javascript(render(:partial => "reports_search"))%>");

app/views/vmrequests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vmrequest.name %>
</p>

<p>
  <b>Environment:</b>
  <%= @vmrequest.environment %>
</p>

<p>
  <b>Requester:</b>
  <%= @vmrequest.requester %>
</p>

<p>
  <b>Requested date:</b>
  <%= @vmrequest.requested_date %>
</p>

<p>
  <b>Cpus:</b>
  <%= @vmrequest.cpus %>
</p>

<p>
  <b>Ram:</b>
  <%= @vmrequest.ram %>
</p>

<p>
  <b>Space:</b>
  <%= @vmrequest.space %>
</p>

<p>
  <b>Os type:</b>
  <%= @vmrequest.os_type %>
</p>

<p>
  <b>Approval:</b>
  <%= @vmrequest.approval %>
</p>

<p>
  <b>Comments:</b>
  <%= @vmrequest.comments %>
</p>

<p>
  <b>Status:</b>
  <%= @vmrequest.status %>
</p>


<%= link_to 'Edit', edit_vmrequest_path(@vmrequest) %> |
<%= link_to 'Back', vmrequests_path %>

app/views/vmrequests/update.js.erb
<%# if remotipart_submitted? %>
$(".landing-container").html("<%= escape_javascript(render(:partial => "index"))%>");

<%# else %>
  // alert('submitted via native jquery-ujs')
<%# end %>