config/routes.rb
LinuxEndpoint::Application.routes.draw do #  get "resumes/index"

 # get "resumes/new"

 #get "resumes/create"

#  get "resumes/destroy"
  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :builds


  resources :projects


  resources :vmrequests


  get "home/index"
get "/search_list" => "home#search_list", :as => :search_list
get "/reports" => "vmrequests#reports", :as => :reports
get "/reports_search" => "vmrequests#reports_search", :as => :reports_search
get "export", to: "vmrequests#export", :as => :export
get "status_export", to: "projects#status_export", :as => :status_export

  get "sessions/new"

  resources :sessions

  match 'logout', to: 'sessions#destroy', as: 'logout'

  match 'login', to: 'sessions#new', as: 'login'

  match 'signup', to: 'users#new', as: 'signup'
   root :to => 'home#index'
end

app/models/build.rb
class Build < ActiveRecord::Base
  attr_accessible :owner, :os_version,  :ticket_no, :project, :approval, :comments, :cpus, :environment, :name, :os_type, :ram, :requested_date, :requester, :space, :status
  searchable do 
  text :name
  text :requester
end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  # GET /builds
  # GET /builds.json
  def index
     @search = Build.search do
      fulltext params[:search]
      paginate  :page => params[:page], :per_page=>6
    end
    @builds = @search.results

  end

  # GET /builds/1
  # GET /builds/1.json
  def show
    @build = Build.find(params[:id])
  end

  # GET /builds/new
  # GET /builds/new.json
  def new
    @build = Build.new

   
  end

  # GET /builds/1/edit
  def edit
    @build = Build.find(params[:id])
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(params[:build])
    p @build
    p @build.id
    p "one printed"
if request.xhr?
  p "in request"
  # raise "here"
    # respond_to do |format|
      # if @build.save
      @build.save
      p @build.id
      p "saved record      "
        # render :js =>"windows.location='builds/index'"
        redirect_to(:controller=>"builds", :action=>"index")
        # format.html { redirect_to @build, notice: 'Build was successfully created.' }
        # format.json { render json: @build, status: :created, location: @build }
      # else
        # format.html { render action: "new" }
        # format.json { render json: @build.errors, status: :unprocessable_entity }
      # end
    end
  # else
  #   raise "in else"
  #   end

  end

  # PUT /builds/1
  # PUT /builds/1.json
  def update
    @build = Build.find(params[:id])

    respond_to do |format|
      if @build.update_attributes(params[:build])
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build = Build.find(params[:id])
    @build.destroy

    respond_to do |format|
      format.html { redirect_to builds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_for(@build, remote: true) do |f| %>
  

  <fieldset class="formfield">
 <p>
    <label> VM Name*</label>
    <%= f.text_field :name %>
  </p>
  
  <% @projects = Project.all%>
   <p>
    <label> Project*</label>
    <%= f.select :project, (@projects.collect{|a| [a.name, a.id]}),{},{:style=>"width:50% !important;"} %>
  </p>
  <p>
    <label>Environment</label>
    <%= f.select :environment, ['Dev','Stage','Prod', 'OneCloud'] ,{},{:style=>"width:50% !important;"}%>
  </p>
  <p>
    <label> Requester Email*</label>
    <%= f.text_field :requester %>
  </p>
  <p>
    <label> Owner</label>
    <%= f.text_field :owner %>
  </p>
  <p>
    <label>Requested Date</label>
    <%= f.date_select :requested_date, :style=>"width:70px;" %>
  </p>
  <p>
    <% cpu = (1..128).select{|i| i%2==0} %>
    <label>CPU's</label>
    <%= f.select :cpus,cpu,{},{:style=>"width:50% !important;"} %>
  </p>
  <p>
    <% rams = (1..1024).select{|i| i%2==0} %>
    <label>RAM (GB)</label>
    <%= f.select :ram , rams,{},{:style=>"width:50% !important;"}%>
  </p>
  <p>
    <% spc = (1..1024).select{|i| i%2==0} %>
    <% spc << "2TB"%>
    <label>Space (GB)</label>
    <%= f.select :space, spc ,{},{:style=>"width:50% !important;"}%>
  </p>
  <p>
    <label>OS Type</label>
    <%= f.select :os_type,['Windows','Linux'],{},{:style=>"width:50% !important;"} %>
  </p>
   <p>
    <label>OS Version</label>
    <%= f.text_field :os_version,{:style=>"width:50% !important;"} %>
  </p>
  <p>
    <label>Ticket No</label>
    <%= f.text_field :ticket_no,{:style=>"width:50% !important;"} %>
  </p>
  <p>
    <label>Approval</label>
    <%= f.check_box :approval ,{:style=>"width: 19px;height:19px;"}, "yes","no" %>
  </p>
 
  <p>
    <label>Status</label>
    <%= f.select :status, ['Built','InProgress','Started'] ,{},{:style=>"width:50% !important;"}%>
  </p>
     <p>
    <label>Comments</label>

    <%= f.text_area:comments, :rows=>4,:columns=>5 %>
  </p>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/builds/_index.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2>Build Requests</h2></div>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">

          <%= form_tag builds_path, :method => :get, :remote=> true do %>
          <%= text_field_tag :search, params[:search],:class=>"span2 search-query"  ,:style=>"height:32px;border:3px solid rgb(221,219,231);border-radius:14px 0 0 14px; margin-right:-10px;", :placeholder =>"Search By VM Name"%>
          <%= submit_tag "Search", :name => nil, :class=>"btn", :style=>"height:32px; border-radius:0 14px 14px 0;" %>
          <% end %>
        </div>
      </div>
       <div class="form-search col-sm-4"><h2><%= link_to 'New Build request', new_build_path, :remote=>true %></h2></div>
    </div>

  <table class="table table-striped tablesorter">

  <tr>
    <th>VM Name</th>
    <th>Requested date</th>
    <th>Approval</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @builds.each do |vmrequest| %>
  <tr>
    <td><%= vmrequest.name %></td>
    <td><%= vmrequest.requested_date %></td>
    <td><%= vmrequest.approval %></td>
    <td><%= vmrequest.status %></td>
    <td><%= link_to 'Show', vmrequest, :remote=>true %></td>
    <td><%= link_to 'Edit', edit_build_path(vmrequest), :remote=>true %></td>
    <td><%= link_to 'Destroy', vmrequest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />



</div>

      <%= paginate @builds, :container => false, :remote=> true %>

app/views/builds/_show.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2><%= @build.name.capitalize%> Details</h2></div>
     
    </div>
<p id="notice"><%= notice %></p>
<fieldset class="formfield">
 <p style="font-size:14px;">
    <label> Name</label>
  <%= @build.name %>
</p>

<p style="font-size:14px;">
  <label>Environment:</label>
  <%= @build.environment %>
</p>

<p style="font-size:14px;">
  <label>Requester:</label>
  <%= @build.requester %>
</p>
<p style="font-size:14px;">
  <label>Owner :</label>
  <%= @build.owner %>
</p>
<p style="font-size:14px;">
  <label>Project:</label>
  <%= Project.where(:id=>@build.project).first.name if @build.project.present? %>
</p>

<p style="font-size:14px;">
  <label>Requested Date:</label>
  <%= @build.requested_date %>
</p>

<p style="font-size:14px;">
  <label>CPU's:</label>
  <%= @build.cpus %>
</p>

<p style="font-size:14px;">
  <label>RAM (GB):</label>
  <%= @build.ram %>
</p>

<p style="font-size:14px;">
  <label>Space (GB):</label>
  <%= @build.space %>
</p>

<p style="font-size:14px;">
  <label>OS Type:</label>
  <%= @build.os_type %>
</p>
<p style="font-size:14px;">
  <label>OS Version :</label>
  <%= @build.os_version %>
</p>
<p style="font-size:14px;">
  <label>Ticket No :</label>
  <%= @build.ticket_no %>
</p>

<p style="font-size:14px;">
  <label>Approval:</label>
  <%= @build.approval %>
</p>

<p style="font-size:14px;">
  <label>Comments:</label>
  <%= @build.comments %>
</p>



<p style="font-size:14px;">
  <label>Status:</label>
  <%= @build.status %>
</p>
</fieldset>
</div>

<%= link_to 'Edit', edit_build_path(@build), :remote=>true %> |
<%= link_to 'Back', builds_path, :remote=>true %>


<style>
.formfield label { padding:4px;margin-top:0px !important; float: left; clear: left; display: block; width: 140px; padding-right: 20px; text-align: left; line-height: 15px; font-size:14px;}

<style>

app/views/builds/edit.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "form"))%>");

  

app/views/builds/index.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "index"))%>");

  

app/views/builds/new.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "form"))%>");

  

app/views/builds/show.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "show"))%>");

  