config/routes.rb
LinuxEndpoint::Application.routes.draw do #  get "resumes/index"

 # get "resumes/new"

 #get "resumes/create"

#  get "resumes/destroy"
  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :builds


  resources :projects


  resources :vmrequests


  get "home/index"
get "/search_list" => "home#search_list", :as => :search_list
get "/reports" => "vmrequests#reports", :as => :reports
get "/reports_search" => "vmrequests#reports_search", :as => :reports_search
get "export", to: "vmrequests#export", :as => :export
get "status_export", to: "projects#status_export", :as => :status_export

  get "sessions/new"

  resources :sessions

  match 'logout', to: 'sessions#destroy', as: 'logout'

  match 'login', to: 'sessions#new', as: 'login'

  match 'signup', to: 'users#new', as: 'signup'
   root :to => 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :other, :team
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    # @search = Project.search do
    #   fulltext params[:search]
    #   paginate  :page => params[:page], :per_page=>6
    # end
    @projects = Project.all
   # @projects = Project.page(params[:page]).per(7)   
    
  end
  def status_export
    @projects = Project.all
    respond_to do |format|
      format.html
      format.xlsx
      format.csv { send_data @builds.to_csv }
      format.xls{ send_data @projects.to_csv(col_sep: "\t") }
    end
  end  

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

      if @project.save
        redirect_to(:controller=>'projects', :action =>'index')
        
      else
        format.html { render action: "new" }
      end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
      redirect_to :action => :index, status:303
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2>Create Task</h2></div>
     
    </div>
<%= form_for(@project, remote: true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset class="formfield">
 <p>
    <label> Name</label>
    <%= f.text_field :name %>
  </p>
  <p>
  <label>Date</label>
  <%= Date.today %>
  </p>
  <!-- <p>
    <%#= f.label :team %><br />
    <%#= f.text_field :team %>
  </p> -->
  <p>
    <label>Description</label>
    <%= f.text_area :other, :rows=>4,:columns=>5 %>
  </p>

   <p>  <%= f.submit :class=>"btn btn-primary", :value=>"Create Task", :remote=>true, :style=>"float:right;"%></p>
<% end %>
</fieldset>

app/views/projects/_index.html.erb
<div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2>Tasks</h2></div>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">

        
        </div>
      </div>
       <div class="col-sm-4"><%= link_to 'Add Task', new_project_path, :remote=>true, :class=>"btn btn-warning",:style=>"text-align:center;font-size:14px;" %>
       <span class="btn btn-warning"><%= link_to "Download as Excel", export_path(format: "xlsx") %></span></div>
      </div>

    </div>
<table  class="table table-hover tablesorter">
  <tr>
    <th style="text-align:center;font-size:19px;">Name</th>
    <th style="text-align:center;font-size:19px;">Date</th>
    <th style="text-align:center;font-size:19px;">Description</th>
    <th colspan=3 style="text-align:center;font-size:19px;"> Actions</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td style="text-align:center;font-size:14px;"><%= project.name %></td>
    <td style="text-align:center;font-size:14px;"><%= project.created_at.strftime("%d-%m-%y") %></td>
    <td style="text-align:center;font-size:14px;"><%= project.other %></td>
    <td style="text-align:center;font-size:14px;"><%= link_to 'Show', project, :remote=>true, :class=>"btn btn-primary"  %></td>
    <td style="text-align:center;font-size:14px;"><%= link_to 'Edit', edit_project_path(project), :remote=>true, :class=>"btn btn-info"  %></td>
    <td style="text-align:center;font-size:14px;"><%= link_to 'Destroy', project,:remote=>true,  method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger"  %></td>
  </tr>
<% end %>
</table>

<br />
      <%#= paginate @projects, :container => false, :remote=> true %>

app/views/projects/_show.html.erb
<div class ="container">
  <!-- Index form Started -->
  <div class="col-sm-12">
    <div class="form-search col-sm-4">
      <h2><%= @project.name.capitalize%> Details</h2></div>
     
    </div>
<p id="notice"><%= notice %></p>
<fieldset class="formfield">
 <p style="font-size:14px;">
    <label> Name</label>
  <%= @project.name %>
</p>

<p style="font-size:14px;">
  <label>Date:</label>
  <%= @project.created_at.strftime("%d-%m-%y") %>
</p>

<p style="font-size:14px;">
  <label>Description:</label>
  <%= @project.other %>
</p>

</fieldset>
</div>

<%= link_to 'Edit', edit_project_path(@project),:remote=>true %> |
<%= link_to 'Back', projects_path,:remote=>true %>

<style>
.formfield label { padding:4px;margin-top:0px !important; float: left; clear: left; display: block; width: 140px; padding-right: 20px; text-align: left; line-height: 15px; font-size:14px;}

<style>

app/views/projects/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th>Other</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.team %></td>
    <td><%= project.other %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Team:</b>
  <%= @project.team %>
</p>

<p>
  <b>Other:</b>
  <%= @project.other %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.js.erb
$(".landing-container").html("<%= escape_javascript(render(:partial => "show"))%>");