config/routes.rb
LinuxEndpoint::Application.routes.draw do #  get "resumes/index"

 # get "resumes/new"

 #get "resumes/create"

#  get "resumes/destroy"
  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :builds


  resources :projects


  resources :vmrequests


  get "home/index"
get "/search_list" => "home#search_list", :as => :search_list
get "/reports" => "vmrequests#reports", :as => :reports
get "/reports_search" => "vmrequests#reports_search", :as => :reports_search
get "export", to: "vmrequests#export", :as => :export
get "status_export", to: "projects#status_export", :as => :status_export

  get "sessions/new"

  resources :sessions

  match 'logout', to: 'sessions#destroy', as: 'logout'

  match 'login', to: 'sessions#new', as: 'login'

  match 'signup', to: 'users#new', as: 'signup'
   root :to => 'home#index'
end

app/views/layouts/_footer.html.erb
<footer>
 
      <h5 align="center"><b>Copyright © 2014 VMware, Inc. All rights reserved.</b></h5>
      <span style="margin-top:-20px;margin-right:10px;float:right">Developed by <b>Vijaya Jyothi Kalangi</b></span>
   
</footer>

app/views/layouts/_header.html.erb
<header style="border-bottom:2px solid black;">
  <div class="container" style="border:0px #900 solid">
    <div class="row">
      <% if @current_user.present? %>
      <div class="col-sm-4" >
        <div class="logo" > 
          <%= link_to (image_tag("vm-logo.jpg")), "/", :id => "logo", :title=>"Back to Home", :style=>"width:35%;margin:0px !important" %>
        </div>
      </div>

<!-- header search -->
<% comment do %>
      <div class="form-search col-sm-4" style="margin-top:20px;">
        <div class="input-append">

          <%= form_tag search_list_path, :method => :get, :remote=> true do %>
          <%= text_field_tag :search, params[:search],:class=>"span2 search-query" ,:style=>"height:32px;border:3px solid rgb(221,219,231);border-radius:14px 0 0 14px; margin-right:-10px;", :placeholder =>"Search Inventory"%>
          <%= submit_tag "Search", :name => nil, :class=>"btn", :style=>"height:32px; border-radius:0 14px 14px 0;" %>
          <% end %>
        </div>
      </div>
<% end %>


      <div class="col-sm-4" align="right" style=" float:right;padding-top:10px;">
        <span><b>Logged in as: </b><%= @current_user %></span><br/>
        <%= link_to "Logout",  logout_path %>
      </div>
    </div><!-- /.container-fluid -->
  </div>

  <% else %>
  <div class="col-sm-6">
    <div class="logo" style="width:45% !important;"> <%= link_to (image_tag("vm-logo.jpg")), "/", :id => "logo" %>  </div>
  </div>
</div>
<% end %>

</header>
<style>
img{
  width:35%;
}
div.logo:hover  {
  /*opacity:0.6;*/
  transform: scale(1.1);
  /*background-size: 150% 150%;*/
}
.navbar .nav>li:hover {
  /*opacity:0.6;*/
  transform: scale(1.1);
  /*background-size: 150% 150%;*/
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowledge Management Portal</title>
  <%= stylesheet_link_tag    "application","bootstrap","extra","jquery-ui", :media => "all" %>
  <%= javascript_include_tag "application" %>
<%= javascript_include_tag :defaults, "rails.validations" %>  
  <%= csrf_meta_tags %>
</head>
<body>


  <div style=" margin:0; padding:0; left:0; right:0;position:absolute">

   <%= render :partial=> "layouts/header" %>
   <div class="container">
   <div style="text-align:center;color:#428bca;"><h3> Submissions </h3></div>
    <%= yield %> 
  </div>
  <%= yield :scripts %>


  <%= render :partial=> "layouts/footer" %>
  <div class="container" style="height:60px"></div>
</div>
</body>
</html>